### ISSUE TITLE
A Plain Copy of SegFormer?

### ISSUE THREAD

**Issue by aka100kvolt** [zxcqlf/MonoViT#4]
@zxcqlf, why your code is 99% similar to SegFormer? But you never mentioned it in your paper.

**Comment by zxcqlf** [comment]
I don’t understand what is you mean? They are different tasks with different network architectures. How did you get the 99%？

**Comment by aka100kvolt** [comment]
> I don’t understand what is you mean? They are different tasks with different network architectures. How did you get the 99%？

I mean you are claiming novelty (i.e., Section 3.2) over the existing work, SegFormer, with moderate modifications from semantic segmentation to depth estimation, but never mentioned the originality of the work that you are relying on.

**Comment by zxcqlf** [comment]
As mentioned in paper, this paper is based on MPVIT, published in CVPR 2022, and other self supervised method, I don’t know segformer

**Comment by zxcqlf** [comment]
If we missed some key papers, we are sorry about it. Because we only pay attention on the paper for depth estimation.

**Comment by aka100kvolt** [comment]
OK, sorry. I am just making comments based on the ViT code in your Repo. Maybe there is a misunderstanding. I will check MPViT for more information. I will close this issue now.

**Comment by zxcqlf** [comment]
It is Ok, and thanks for your attention.
