### ISSUE TITLE
Lost encoder.pth in mono_1024x320

### ISSUE THREAD

**Issue by Ecalpal** [zxcqlf/MonoViT#6]
Thanks for your work! @zxcqlf 

It seems that the encoder.pth is not included in [here](https://drive.google.com/drive/folders/1EDTSZ59CGW9rUoDL3EwEKn3PpZpUUGsS?usp=sharing)

**Comment by zxcqlf** [comment]
Note that please use evaluate_depth.py for 640x192 models and evaluate_hr_depth.py --height 320/384 --width 1024/1280 for the others. See evaluate_hr_depth.py and networks/nets.py for more details!

**Comment by Ecalpal** [comment]
The habitual thinking from monodepth2 misled me.

Thanks for your reply!
