### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by Itto1992** [zxcqlf/MonoViT#7]
Thank you for your great work! Could you tell me the license for this repository?
Thank you in advance.

**Comment by zxcqlf** [comment]
Hi, we have added the MIT license doc. 
Note that if you use the rest of the monodepth2 code, you should follow the monodepth2 license, too.
Thanks.

**Comment by Itto1992** [comment]
Thank you for your quick response!
I will close this issue.
