### ISSUE TITLE
Which net to use for pose network?

### ISSUE THREAD

**Issue by fangliancheng** [zxcqlf/MonoViT#8]
Thanks for the great work and open source your code!  

I have a question about the pose network: which network should I use for the pose network? According to paper I should use a 'lightweight ResNet18', but I fails to find it in the repo, the posecnn used in monodepth2 seems not a ResNet, is there something I miss?

Best regards,
Liancheng

**Comment by zxcqlf** [comment]
For the pose network, please follow the way in monodepth2, I think it is clearly described in the paper.
