### ISSUE TITLE
A evaluation for Driving Stereo Dataset

### ISSUE THREAD

**Issue by wangjiyuan9** [zxcqlf/MonoViT#9]
Dear author,

Thank you for your fantastic contribution. I noticed that you mentioned the results for the Drivingstereo dataset in the paper. However, I cannot locate any corresponding code for this dataset. The Drivingstereo dataset is different from the Kitti dataset and does not have a toolkit for loading :(

Thank you for your time and assistance!

**Comment by zxcqlf** [comment]
Hi, all you need is to write a data loader for DS dataset, if you donot know how to write it, you can follow the kitti _data_loader. Then, both the depth gt processing method and the evaluation are the same as monodepth2.

Thanks
